---
stages:
  - lint
  - test
  - build
  - publish

include:
  - project: ngreese/job-templates
    ref: main
    file:
      - templates/rust.yml

format:
  extends: .cargo_fmt

clippy:
  extends: .cargo_clippy

tests:
  needs: [format, clippy]
  extends: .cargo_test

build:
  needs: [tests]
  extends: .cargo_build

release:
  needs: [tests]
  extends: .cargo_build_release

publish:
  needs: [release]
  extends: .cargo_publish